### ISSUE TITLE
Finish edition of template texts

### ISSUE THREAD

**Issue by ianrrees** [WandererFan/FreeCAD-TechDraw#18]
Moving this over from ianrrees/FreeCAD_tinkering - was made ~6 months ago, so there's a good chance some of these items have been taken care of.
- Python interface - changing strings, also setting view orientation while there
- Show PropertyMap in PropertyEditor?
- Escape user strings + handle SVG errors better (currently throws unhandled exception)
- DXF support?
- Add blank template option, would be good for error cases like above
- Bigger minimum size for template string dialog
- Don't draw dotted box on SVG render

**Comment by WandererFan** [comment]
- dotted box is now a green edit handle.  
- A?_Landscape_plain.svg for blank template??

**Comment by WandererFan** [comment]
"Python interface - changing strings, also setting view orientation while there"
- Py functions for getting/setting EditableText strings added. 
- Don't understand view orientation for Template  

"Bigger minimum size for template string dialog"  
- Real QDialog with room for fieldnames/content added.  QInputDialog::getText is too hard to beautify.  

"Show PropertyMap in PropertyEditor?"   
- don't need for TechDraw.  eventually all property types should be in editor  

"Escape user strings + handle SVG errors better (currently throws unhandled exception)"   
- don't understand this one.

**Comment by ianrrees** [comment]
View Orientation - I'm not sure if it's important anymore, but there's a Property associated with the template orientation.  Was thinking we should have Python methods for manipulating that (or do those come for free?)

Escaping user strings and handling SVG errors - For instance, try changing a drawing/template title to "Hello <!--" - it'll crash the Qt SVG renderer.  We should both catch the exception thrown in this case (as it could occur when a corrupt SVG is opened) and also escape the string so that it's OK to put those sort of characters in to the text fields.  I imagine there's something built in to Qt for that sort of escaping already, haven't looked.

**Comment by WandererFan** [comment]
App.ActiveDocument.myPage.Template.ViewOrientation = "Landscape" should
work (or ... = 1 since it is an enum).

Might need recompute() after to see results.

OK, I understand the SVG thing now.

Thanks.

**Comment by WandererFan** [comment]
"DXF support?" 
- I'm going to say leave this for now.  There are DXF to SVG converters if somebody really needs to use a DXF based template.

**Comment by WandererFan** [comment]
"Escape user strings + handle SVG errors better (currently throws unhandled exception)" 

**\* fixed

**Comment by WandererFan** [comment]
Everything on this list except:
- PropertyEditor changes fore PropertyMap
- DXF template support 
  is fixed, so I'm going to close this issue.
