### ISSUE TITLE
Rendering of large-scale objects

### ISSUE THREAD

**Issue by ianrrees** [WandererFan/FreeCAD-TechDraw#19]
Things get really slow when a Drawing of a really big sphere (r=500km) is requested - investigate this.

From vague memory, the issue is that we initially try to draw the item at document scale, and the canvas gets expanded to some absurd pixel dimension (which takes the time).

**Comment by WandererFan** [comment]
Autoscale at creation?  if BBox >> PageSize,  Scale == 1/(BBox/PageSize)

What about if BBox << PageSize?  Magnify it?

**Comment by ianrrees** [comment]
I like the idea of defaulting to auto scale when adding items to the drawing in general.  Maybe it using the logic from the current auto scale that picks "standard" scaling values.

Agree that small items should scale up.  IIRC that is less of a problem since it doesn't cause the slowdown.  Do we run in to problems with tolerances on selection of really small items?

**Comment by WandererFan** [comment]
Hey, good to here from you! I was just thinking about sending a ping.

Scaling to best fit standard size sounds good.

Should be ok with the OCC stuff.  It mostly uses Precision::Confusion(), I
think.  Was never 100% sure what the TD Precision property was for.

**Comment by WandererFan** [comment]
fixed.  master commit cf90d6931914bb1f7a0cdb1eefd27b14e23bf458
