### ISSUE TITLE
Can't save when the drawing viewer is selected

### ISSUE THREAD

**Issue by ianrrees** [WandererFan/FreeCAD-TechDraw#21]
When I'm using the Drawing Viewer, if I go File->Save or File->Save As, nothing happens.  Have to switch back to the normal 3D viewer to save a document.  Is this is a Mac-only issue?

**Comment by ianrrees** [comment]
Needed to call SaveAs on the GUI Document in MDIViewPage::onMsg()

**Comment by WandererFan** [comment]
Great!
