### ISSUE TITLE
Provide for "Hole Table"

### ISSUE THREAD

**Issue by ianrrees** [WandererFan/FreeCAD-TechDraw#35]
Splitting this one out from https://github.com/WandererFan/FreeCAD-TechDraw/issues/28

From efyx83: for example: https://www.solidsolutions.co.uk/Uploaded/Image/BLOG-PICS/BarryChatham/solidworks-HoleTable-Blog.png)

And: https://www.youtube.com/watch?v=wGxgfFKf1HU

**Comment by WandererFan** [comment]
This can be done with DrawViewSpreadsheet.
