### ISSUE TITLE
C++11

### ISSUE THREAD

**Issue by ianrrees** [WandererFan/FreeCAD-TechDraw#44]
@WandererFan, what do you think about using a bit more C++11 in TechDraw?  I'd personally like to use it, but know you're still running an older gcc so it might be a pain to switch on your end.

**Comment by WandererFan** [comment]
I'm just trying to recompile with g++-4.9 (+std=C++11) and boost 1.55.
I'll let you know how I make out.

**Comment by WandererFan** [comment]
Compiled successfully with g++-4.9 and boost 1.55.  Had to make a change to
Inventor/SbBasic.h to get it to work.  Looks like this error:
http://forum.freecadweb.org/viewtopic.php?t=14108&start=10
 (cc_debugerror_post).  Think that is boost related, not c++11.  Also lots
of warnings in other modules.

So I can work with c++11.  Will it be a problem for testers?

**Comment by ianrrees** [comment]
I don't imagine it'll be a problem for too many people - if it does cause problems, they're just foreshadowing issues with building the FreeCAD master soon.

We'll see how it goes, shouldn't be a big deal to back out problematic changes.
