### ISSUE TITLE
TechDraw compilation - no workbench

### ISSUE THREAD

**Issue by 3h600** [WandererFan/FreeCAD-TechDraw#50]
Hi,
I compiled two times source from https://github.com/WandererFan/FreeCAD-TechDraw and I couldn't find techdraw module. Any idea why. I configure it with cmake-gui (no option techdraw to select, all others modules are available).

**Comment by ianrrees** [comment]
Sounds like you have the git repository's "master" branch checked out, but need the "TechDraw" one.  In a terminal, if you cd to the git repository (it'll likely be called some-path/FreeCAD-TechDraw ) and do "git status" it will tell you what branch you're on.  "git checkout TechDraw" will put you on the TechDraw branch.

There are also GUI programs for working with git, I use SourceTree a bit and like it.

**Comment by WandererFan** [comment]
The TechDraw build option is at line 201 in the main CMakeLists.txt.

**Comment by WandererFan** [comment]
We can reopen this one if it is still a problem, but I think there's nothing for us to do.

**Comment by liutas4x4** [comment]
Hi

After unzipping from FreeCAD_0.17.7745_x64_dev_win.7z I cannot fount TechDraw workbench too

**Comment by WandererFan** [comment]
I've posted your issue on the FreeCAD forum: http://forum.freecadweb.org/viewtopic.php?f=4&t=16687
Check there for updates.

Thanks.
